- hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH connection
      wait_for_connection:
        delay: 10
        timeout: 300
        sleep: 20
    - name: install packages
      include: tasks/install.yml
    - name: setup network
      include: tasks/setup_network.yml
